services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: yield2pay
      POSTGRES_USER: yield2pay
      POSTGRES_PASSWORD: yield2pay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
